name = "karaoke-queue"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KARAOKE_KV"
id = "31425b61dea34153afd11f446c29b456"

[[migrations]]
tag = "v2"
deleted_classes = ["KaraokeQueue"]
